


services:
  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
    depends_on:
      - web

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data:
