version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./scripts/dockerfiles/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      web:
        condition: service_healthy
    command: ["nginx", "-g", "daemon off;"]

volumes:
  static_volume: